create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  food_name text not null,
  price numeric(10, 2) not null,
  quantity integer not null check (quantity > 0),
  total numeric(10, 2) not null,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;

create policy "Allow anyone to place an order"
on public.orders for insert
to anon
with check (true);